-- MySQL Script generated by MySQL Workbench
-- Sun Aug  7 22:28:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Grados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grados` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Grado` VARCHAR(45) NOT NULL,
  `Seccion` VARCHAR(45) NOT NULL,
  `Tutor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiantes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido_Paterno` VARCHAR(45) NOT NULL,
  `Apellido_Materno` VARCHAR(45) NOT NULL,
  `Id_Grado` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Id_Grado_idx` (`Id_Grado` ASC) VISIBLE,
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  CONSTRAINT `Id_Grado_Estudiante`
    FOREIGN KEY (`Id_Grado`)
    REFERENCES `mydb`.`Grados` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Materias` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Id_Grado` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Id_Grado_idx` (`Id_Grado` ASC) VISIBLE,
  CONSTRAINT `Id_Grado_Materias`
    FOREIGN KEY (`Id_Grado`)
    REFERENCES `mydb`.`Grados` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notas` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Id_Estudiante` INT NOT NULL,
  `Id_Materia` INT NOT NULL,
  `Calificacion` FLOAT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Id_Estudiante_idx` (`Id_Estudiante` ASC) VISIBLE,
  INDEX `Id_Materia_idx` (`Id_Materia` ASC) VISIBLE,
  CONSTRAINT `Id_Estudiante`
    FOREIGN KEY (`Id_Estudiante`)
    REFERENCES `mydb`.`Estudiantes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Id_Materia`
    FOREIGN KEY (`Id_Materia`)
    REFERENCES `mydb`.`Materias` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
